spring:

  datasource:

    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name: exchange-service

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
